[book]
authors = ["Ratul Buragohain"]
language = "en"
multilingual = true
src = "src"
title = "Programming Problems & Data Structures in Rust"
description = "Programming Problems & Data Structures in Rust"

[build]
build-dir = "docs"

[output.html]
additional-css = ["theme/custom.css"]
default-theme = "navy"
preferred-dark-theme = "navy"

